---
- name: Fail if distribution is not Ubuntu
  fail:
    msg: Invalid operating system
  when: ansible_distribution != 'Ubuntu'

- name: Install Microsoft apt repository
  apt:
    deb: "{{ apt_microsoft_repository }}"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install application prerequisites
  apt:
    name:
      - unzip
      - apt-transport-https
      - dotnet-sdk-2.2
    state: latest
  become: yes

- name: Create application user
  user:
    name: "{{ app.user }}"
    comment: User for netcoreapp
    state: present
  become: yes

- name: Download application binaries
  get_url:
    url: "{{ app.download_url }}"
    dest: "{{ app.download_path }}"
    owner: "{{ app.user }}"
    group: "{{ app.user }}"
  become: yes
  become_user: "{{ app.user }}"

- name: Create application installation folder
  file:
    path: "{{ app.installation_path }}"
    state: directory
    owner: "{{ app.user }}"
    group: "{{ app.user }}"
  become: yes
  become_user: "{{ app.user }}"

- name: Unzip the application
  unarchive:
    src: "{{ app.download_path }}"
    dest: "{{ app.installation_path }}"
    remote_src: yes
  become: yes
  become_user: "{{ app.user }}"

- name: Install Linux service
  template:
    src: netcoreapp.service.j2
    dest: /etc/systemd/system/netcoreapp.service
  become: yes

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes
  become: yes

- name: Start & enable the application
  systemd:
    name: netcoreapp
    state: restarted
    enabled: yes
  become: yes