---
- name: Fail if distribution is not Ubuntu
  fail:
    msg: Invalid operating system
  when: ansible_distribution != 'Ubuntu'

- name: Install Microsoft apt repository
  apt:
    deb: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install application prerequisites
  apt:
    name:
      - unzip
      - apt-transport-https
      - dotnet-sdk-2.2
    state: latest

- name: Create application user
  user:
    name: netcoreapp
    comment: User for netcoreapp
    state: present

- name: Download application binaries
  get_url:
    url: https://uipathdevtest.blob.core.windows.net/binaries/netcoreapp2.2.zip
    dest: /home/netcoreapp/netcoreapp2.2.zip
    owner: netcoreapp
    group: netcoreapp

- name: Create application installation folder
  file:
    path: /home/netcoreapp/installation
    state: directory
    owner: netcoreapp
    group: netcoreapp

- name: Unzip the application
  unarchive:
    src: /home/netcoreapp/netcoreapp2.2.zip
    dest: /home/netcoreapp/installation
    remote_src: yes

- name: Install Linux service
  template:
    src: netcoreapp.service.j2
    dest: /etc/systemd/system/netcoreapp.service

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Start & enable the application
  systemd:
    name: netcoreapp
    state: restarted
    enabled: yes